### ISSUE TITLE
エラーレスポンスのコード取得について

### ISSUE THREAD

**Issue by takuyama29** [payjp/payjp-android#11]
現在こちらのSDKを導入して以下の様にエラータイプもしくはエラーコードの取得を行おうとしているのですが、[エラーハンドリング](https://pay.jp/docs/api/#error)に記載されている様なスネークケースの結果にアクセスすることができまんせん。

使用したリクエストカード番号: 4000000000000002
```kotlin
PayjpToken.getInstance().createToken(
                requestCreditCard.cardNumber,
                requestCreditCard.cardCvc,
                requestCreditCard.cardExpirationMonth,
                requestCreditCard.cardExpirationYear)
                .enqueue(object : Task.Callback<Token> {
                    override fun onSuccess(data: Token) {
                        Log.i("MainActivity", "token => $data")
                    }

                    override fun onError(throwable: Throwable) {
                        if (throwable is PayjpApiException) {
                            val exception = throwable as PayjpApiException
                            Log.e("MainActivity", exception.httpStatusCode.toString())
                            Log.e("MainActivity", exception.apiError.toString())
                            Log.e("MainActivity", exception.localizedMessage)
                            Log.e("MainActivity", exception.message)
                        }
                        Log.e("MainActivity", "throwable", throwable)
                        Log.e("MainActivity", throwable.message)
                    }
                })
```

```Logcat
// Logcat
E/MainActivity: 402
E/MainActivity: ApiError(message=Card declined)
E/MainActivity: Card declined
E/MainActivity: Card declined
E/MainActivity: throwable
                jp.pay.android.exception.PayjpApiException: Card declined
                at jp.pay.android.network.ResultCall.generateHttpError(ResultCall.kt:49)
                at jp.pay.android.network.ResultCall.access$generateHttpError(ResultCall.kt:42)
                at jp.pay.android.network.ResultCall$enqueue$2$onResponse$1.run(ResultCall.kt:80)
                at android.os.Handler.handleCallback(Handler.java:789)
                at android.os.Handler.dispatchMessage(Handler.java:98)
                at android.os.Looper.loop(Looper.java:164)
                at android.app.ActivityThread.main(ActivityThread.java:6541)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/MainActivity: Card declined
```

想定では`card_declined`が返ってくるものと思いプロパティを探していますが、`Card declined`の様なフォーマットのメッセージしか見つけることができませんでした。

レスポンスへのアクセスの仕方が悪いかと思いますので、エラーハンドリングに記載のあるようなスネークケースのメッセージを受け取る方法を教えていただければと思います。

**Comment by yatatsu** [comment]
レポートありがとうございます。
現在のSDK（`v0.1.0`）ではレスポンスのエラーオブジェクトを隠蔽しており、APIから返却された`card_decliened`というプロパティを取得することができません。
エラーコードに簡易にアクセスできるように改善いたします。

**Comment by takuyama29** [comment]
返信ありがとうございます！
承知しました。今後のアップデートを心待ちにしております。

**Comment by yatatsu** [comment]
先程 `0.1.1` をリリースしました。
https://github.com/payjp/payjp-android/releases/tag/0.1.1

```build.gradle
implementation 'jp.pay:payjp-android:0.1.1'
```

今回のアップデートで、ご指摘頂いていた件について `ApiError#code` というかたちで取得出来るようになっております。エラーの分類を表すタイプについても `ApiError#type` でアクセスできます。

```kotlin
override fun onError(throwable: Throwable) {
    if (throwable is PayjpApiException) {
        val exception = throwable as PayjpApiException
        Log.e("MainActivity", exception.httpStatusCode.toString()) // -> e.g. "402"
        Log.e("MainActivity", exception.apiError.code) // -> e.g. "card_declined"
        Log.e("MainActivity", exception.message) // -> e.g. "Card declined"
        Log.e("MainActivity", exception.apiError.type) // -> e.g. "card_error"
        Log.e("MainActivity", exception.cause::class.java) // -> retrofit2.HttpException
        Log.e("MainActivity", exception.source) // -> e.g. "{ \"error\": { } }" (raw json)
    }
}
```

具体的な変更内容は #12 になります。
もし不明点や誤りなどがあれば、ご指摘いただけると幸いです。
よろしくお願いします。

**Comment by takuyama29** [comment]
@yaakaito 
迅速な対応に感謝します！
大変助かりました。
